name = "HyperbolicNumbers"
uuid = "1063c4aa-4f19-47e3-87f6-d15aa8c8d36c"
version = "0.1.0"
authors = ["Elletri"]

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1.3.4"
